### ISSUE TITLE
Cant open Browser by 901"Error PeekNamedPipe in readProcCDP."

### ISSUE THREAD

**Issue by Chemiphys** [longvh211/Chromium-Automation-with-CDP-for-VBA#13]
i want use this addin,but i cant do it.
when execute "Run Edge" in Demo module
![errormsg](https://github.com/longvh211/Chromium-Automation-with-CDP-for-VBA/assets/27146682/662c6b28-616b-4689-816a-0844492d7999)
![local](https://github.com/longvh211/Chromium-Automation-with-CDP-for-VBA/assets/27146682/dd61d508-b47d-4324-9a16-e79eb63084fd)
![stoppoint](https://github.com/longvh211/Chromium-Automation-with-CDP-for-VBA/assets/27146682/34a00f15-61a1-4ffe-9952-e1a6be40a4eb)
stop by this error,what is my mistake?
teach me please.

**Comment by Chemiphys** [comment]
self-Resolution
vba option    Suspend when an error occurs option  

after change this setting,i can use this libraly thx.

sorry i cant write english well

**Comment by longvh211** [comment]
My apologies for the late reply but I am glad you have found the resolution yourself.

**Comment by rocketlaw** [comment]
Wait. What do you mean "vba option Suspend when an error occurs option"?  Is it "onError" "Suspend"??? I ain't that code savvy.

**Comment by longvh211** [comment]
Hi rocketlaw, what Chemiphys meant is this option in VBA editor:

<img width="414" alt="image" src="https://github.com/longvh211/Chromium-Automation-with-CDP-for-VBA/assets/37789938/f3278dd2-5f1e-47fd-8425-9ae7c7fb5194">

If you set them to anything else beyond Unhandled Errors, that line will cause exception all the time.

**Comment by Jonny125** [comment]
Hello @longvh211, 
I have the same issue as Chemiphys, however my settings in the general-tab of the VBA-editor options are the same as pictured in your screenshot.

Do you know why this is happening?

Any help is highly aprreciated.

**Comment by longvh211** [comment]
Did any of the demo examples work for you?
