### ISSUE TITLE
use current instance

### ISSUE THREAD

**Issue by tonton81** [longvh211/Chromium-Automation-with-CDP-for-VBA#17]
this code seems to be at least communicating with chrome compared to others i tested, which is great!

I'm just trying to figure it out but i set the reAttach:=True flag from chrome, which works fine, however, if i start chrome before the code, it actually restarts the browser, even though i have the browser flags set for debugging. But if the browser was already loaded using the code, it reAttaches to same one. Is this intentional or can it not use a browser already in debugging mode before requiring resetting it?

**Comment by longvh211** [comment]
Hi tonton, if you start chrome manually, that chrome session is not known to CDP and causes the CDP pipe to fail to initialize. The CDP framework at the moment only works with running session started by the framework itself.

**Comment by tonton81** [comment]
i see.. in any case this is the closest thing i got working, guess i'll live with the pipe method, i was used to the debug 9222 in ahk so it's a bit different there 🙂
