### ISSUE TITLE
InnerHTML

### ISSUE THREAD

**Issue by chrisdaniels** [longvh211/Chromium-Automation-with-CDP-for-VBA#3]
Hi again

Are you are to assist with this command at all please? 

It works in the Chrome console as 
`document.Evaluate("//body", document.body, null, 9, null).singleNodeValue.innerHTML` 
but in VBA it returns null - i've tried all kinds of variations.

VBA:
`Body = tab2.jsEval("document.Evaluate(""//body"", document.body, null, 9, null).singleNodeValue.innerHTML")`

I need to pass the innerHTML to Excel in order to extract several tables of data.

**Comment by longvh211** [comment]
Hi Chris,

Maybe try:

`tab2.jsEval("x = document.Evaluate(""//body"", document.body, null, 9, null).singleNodeValue.innerHTML")
Body = tab2.jsEval("x")`

**Comment by chrisdaniels** [comment]
Thank you

I've got it working - it was because document.evaluate is case sensitive!
