### ISSUE TITLE
Facing issue with cdpjconv 

### ISSUE THREAD

**Issue by jianyuan941** [longvh211/Chromium-Automation-with-CDP-for-VBA#35]
When I try to run the demo, there is a compile error: user-defined type not defined. 

Then highlighted private function Jason_parseobject (json_string as string, byref json_index as long) as scripting.dictionary 

May I know how to solve it. Thanks alot ![IMG_20241113_012652.jpg](https://github.com/user-attachments/assets/df4e6612-52d4-449b-9f20-fa4f8bbddc3a)

**Comment by longvh211** [comment]
Hi, simply enable Microsoft Scripting Runtime in the VBA References.

**Comment by jianyuan941** [comment]
Thanks !!!
