### ISSUE TITLE
Wait Method in clsBrowser Class sometimes doesn't work.

### ISSUE THREAD

**Issue by murrayJc** [longvh211/Chromium-Automation-with-CDP-for-VBA#5]
I found that sometimes the wait method fails to wait the required time before moving on to the next routine. I had to add a 1 second sleep (0.5 seconds might work just as well) time at the top of the routine. I attributed this to the slow response time from command initiation to the time the method looked for the status change.  I noticed this while trying to manipulate an HTML <Select> Tag.  and immediately changing an <input> tag to update their values.  Neither Tag would update to the new value. 

Changes Needed to rectify the problem:  [ =>]

  =>   sleep 1    '/ Add an initial delay to allow status to change. JEM 11-30-22
    
    Do Until strState = till Or strState = "complete"
        strState = jsEval("document.readyState", dbgMsg:=False)         ' dbgMsg = False to not spam Immediate Window
        If dbgState Then Debug.Print "Current ReadyState: " & strState  ' option to print ReadyState info during iteration
        sleep 0.1                                                       ' reduce sleep will speed up but will cost cpu power
    Loop
    
End Function

**Comment by longvh211** [comment]
Thanks murray for suggesting this. I agree adding the sleep method here is an efficient and effective improvement too. I will add this to the release.
