### ISSUE TITLE
Browser Window is Visible at Start up before  .Show Method is issued

### ISSUE THREAD

**Issue by murrayJc** [longvh211/Chromium-Automation-with-CDP-for-VBA#6]
The browser window becomes visible when the Start Method is initiated. This is not desired. 

Discovered that by changing the wShowWindow property in the init Function from SW_SHOWMINIMIZED to 11 (SW_FORCEMINIMIZE), the Window stays hidden until the show method is issued.  In order for this to be reliable,  the hide method has to be issued 1st immediately after the start method . For whatever reason, it doesn't work unless you issue the hide command. This seems to be a workaround. 

Adding a me.hide at the bottom of the Attach method seems to make everything work transparently without the need to add the hide command for each new logic block. 

```
========================================================
Public Function init(strExec As String, Optional aboolSerializable As Boolean = False) As Integer
    .
    .
    .
   'Define new instance parameters and start it
    With Start
        .cb = Len(Start)
        .dwFlags = STARTF_USESHOWWINDOW
        .hStdOutput = hStdOutWr
        .hStdInput = hStdInRd
        .hStdError = hStdOutWr
===>         .wShowWindow = 11  'SW_SHOWMINIMIZED 'minimize the window at start
        .cbReserved2 = Len(pipes2)
        .lpReserved2 = VarPtr(pipes2)
    End With
========================================================


Private Function attach(Optional strUrl As String = "") As Integer
    .
    .
    .

    timeEnd = Timer
    Debug.Print "Attached successfully after " & Format(timeEnd - timeStart, "0.000") & "ms"
=======>Me.hide 
End Function
```

**Comment by longvh211** [comment]
Thanks murrayjc for this. Really appreciate it. I also noticed this issue before but have not had the time to look at it thoroughly. I will incorporate your suggestion in the next update. If you have the time, would you be able to look at the issue with the browser windows resizing failure in some of the demo examples?
