### ISSUE TITLE
Finding URL with browser already running

### ISSUE THREAD

**Issue by YN32** [longvh211/Chromium-Automation-with-CDP-for-VBA#7]
Anh Long - Thanks to you I have successfully converted my codes to work with Edge IE mode.  Unfortunately, good thing does not last long because the website that I interacted with no longer support IE mode.  I am looking into using CDP.

From your and PerditionC examples, it seems CDP is unable to manipulate webpage that already launched.  That is, the examples always show that the browser needs to be closed before you can start a new session.  Each time I tried to set the cleanActiveSession:=False, it gave me an error.  Is it true that that we cannot manipulate the existing webpage (i.e. finding URL) if the (chrome) browser is already running when using CDP?  Could you explain why if this is the case?

**Comment by PerditionC** [comment]
It depends on how the browser was started.  Currently in VBA the best means to communicate with the browser is through file handle based I/O where we spawn the browser with it's default (stdin/stdput, ...) handles are opened to a handle that VBA can do nonblocking I/O with.  There is no other way to create this communication channel other than spawning the browser as a child process, hence the need to be the one to launch the browser.  Now VBA can also talk to the browser through websockets.  This is how it is usually done from other languages and will allow talking to an existing browser session assuming it was started with the commands to listen on a websocket.  I do not believe you can tell an existing browser process to start listening so it must be done when initially launched - though I may be mistaken on this.  However, using websockets in VBA causes lockups while waiting for the browser as the current implementation uses a Windows API which does not support nonblocking I/O.  That is the VBA runtime blocks when checking for messages from the browser which in turn causes the hosting application like Excel to appear unresponsive.

**Comment by longvh211** [comment]
Thank you Kenneth @PerditionC for the very helpful and thorough reply as well as your framework with a lot of examples in it. I really appreciate it. @YN32 this is a known setback but comes with an easy work around: as long as user initializes the browser with CDP framework, it can be re attached later on. Correct me if I am wrong but I think this is a commonly shared difficulty with chromium browser. Even with Selenium, we are not able to automate a session not started by Selenium.

**Comment by YN32** [comment]
Thank you both - K. PerditionC and A. Long!  Regarding PerdictionC's comment, I will stick with the CDP framework instead of websockets since the chance of Excel to be unresponsive is high.
Regarding A. Long's comments, you stated that it can be reattached later on...is this mean, the trick is to save the serialized string to cell(1,1) as in one of your example?  If so, here is the issue:  Users perform data entry and run reports throughout the day using website "A".  The website "A" logs out within 10 minutes if users do not interact with the site.    I have not tried it yet but assume that the serialized string in cell(1,1) will no longer be valid because the page change to "your session has been logged out."  Please assist if there is another way to reattached the site without shutting down chrome.

**Comment by longvh211** [comment]
- @YN32 Kenneth was actually explaining how the CDP Framework works with the Chromium engine. For the issue of the target web application logging out once in a while, usually it does not close the entire browser window. Hence you can still make use of the browser window to essentially open the same web application link to load it up again. The serialized string pertains to the entire browser window, not just the tab the browser is operating. Hope that shall help you get an idea on how to manage it!

**Comment by longvh211** [comment]
@YN32 first you need to inspect the HTML to identify what exactly that popup is. If it is an iframe, you will have to use an iframe-related JS method to interact with the elements inside that frame. If the interaction opens the link to another tab then you can apply the example in the demo to manage the new tab with CDP automation as well.
