### ISSUE TITLE
Recent antivirus update blocking code

### ISSUE THREAD

**Issue by TheRedBar** [longvh211/Chromium-Automation-with-CDP-for-VBA#8]
Hello. You're code is amazng and I have been using it daily for the past month. Unfortunately, as of this week, my work antivirus is blocking the VBA as soon as it tries to execute the line "EnumWindows AddressOf EnumWindowsProc, 0&". By any chance, is there any alternative solutions?

**Comment by longvh211** [comment]
Hi there. Thank you for the feedback, I will be releasing the next version of CDP framework too so do keep a look out for it. I cannot seem to find that code line which you mentioned in the framework. Where is it?

**Comment by TheRedBar** [comment]
Great, I look forward to checking it out! As far as that line, I might have posted on the wrong git, however it’s in your Edge-IE-Mode-Automation-with-IES-for-VBA > core.bas line 102. V/RJustin Johnson On Apr 6, 2023, at 9:30 PM, Long Vh ***@***.***> wrote:﻿
Hi there. Thank you for the feedback, I will be releasing the next version of CDP framework too so do keep a look out for it. I cannot seem to find that code line which you mentioned in the framework. Where is it?

**Comment by longvh211** [comment]
I see. For IES, that is the only method to target the Chrome_WidgetWin window. You will have to report the issue to your IT I suppose so that the antivirus can allow the enumeration. Otherwise, how about making the changes to the Registry so that you can natively interact with Edge IE mode?
